### ISSUE TITLE
Erreur npm run

### ISSUE THREAD

**Issue by noelma** [Florian-Merle/el-demo#2]
Bonjour,

Après avoir installé votre projet, lancer l'installation des dépendances avec un npm install, la commande `npm run build` m'annonce les erreurs suivantes:

```shell
~/www/el-demo (master*) » npm run build

> build
> encore production --progress

Running webpack ...

[webpack-cli] Failed to load '/home/noelma/www/el-demo/webpack.config.js' config
[webpack-cli] /home/noelma/www/el-demo/node_modules/jest-worker/build/index.js:126
      enableWorkerThreads: this._options.enableWorkerThreads ?? false,
                                                              ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/noelma/www/el-demo/node_modules/css-minimizer-webpack-plugin/dist/index.js:17:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

Pourriez-vous ajouter un readme avec les prés requis et une procédure d'installation pour pouvoir étudier votre démo ? Merci :heart_decoration:

**Comment by Florian-Merle** [comment]
J'ai ajouté un readme avec les versions des différents outils que j'ai utilisé pour la démo, en espérant que ça vous permette de faire tourner la démo sur votre machine :)
